### ISSUE TITLE
Hide sidebar option into hamburger menu when opening the website on mobile phone

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#103] opened 2023-08-29 15:17 UTC
Hide the sidebar option into the hamburger menu when opening the website on a mobile phone

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/7cf2fab2-9da3-4edc-a70a-b455f48d7940)

**Comment by liza-veis** [comment] 2023-08-29 18:10
Pay attention to this issue #91, so that it doesn't break your implementation

**Comment by oksana-mlynska** [comment] 2023-09-03 07:02
@Nanaier I am trying to check the root page on phone dimensions, but I don't see any menu at all, just blank page. Could you also check it?



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/274147d8-6eef-4ead-8597-2bccff7895e5)

**Comment by Nanaier** [comment] 2023-09-03 07:12
@oksana-mlynska this is an expected behavior for now, since we don’t have a header on our page and our hamburger menu is located there - I’ve informed @Liza-Veis about it already

**Comment by oksana-mlynska** [comment] 2023-09-03 07:21
@Nanaier ok, thanks for clarification. Then I guess due to the fact that hamburger menu is present on the header on the Survey page I can close this issue


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/e5780568-e91a-42d2-b1ed-d4788e29754d)

**Closed as completed** 2023-09-03 07:24 UTC
Labels: frontend, cp-v1
